apiVersion: ENC[AES256_GCM,data:HNg=,iv:0ort+ArODJStP3kilGOP1DmTsf4Bh0XsfeIbwu3gffs=,tag:pW1aKwVOk9wqoCWZm12V8w==,type:str]
kind: ENC[AES256_GCM,data:1FNWcFFd,iv:r+dVLBdDVfIf8gO7JodmneCGvT/DA5W10FjBRCzpnRE=,tag:RbZVi4WanE1SSa2CXuY0xA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sYP1WzshYxjqcJuV+xVi,iv:3o10hpbskDfCcijeH234PdyFhsgkLvQfk+yAVy7DB/g=,tag:iVtDG14zS3x6u8nQ+PuCFw==,type:str]
    namespace: ENC[AES256_GCM,data:hI4SC84=,iv:358IyT7SCLAUBT3JtRc3cWNNWixqp/RnzT2Nrc2bCwY=,tag:66XwFHpkvemHVDGzoffIlw==,type:str]
type: ENC[AES256_GCM,data:o1ZEcJA3,iv:jj5XhLEBqcux7yNFVXjQ2qplJo/OLq3gzsuTSsEeXgs=,tag:nK2cHNJez9/+2e4q0PUWHw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:A9E+msO98kWdSbUVM0fupLCV760v244iEECX6VHZmgZk0xvrUhm6nZYDBy87APB+1Hp6Cfw+TSjthBacKFnfnydJX31dEFd/iR6bHVGFdbZUkkq42E5bx0/DftYF/RvFqtZMM9FBbT7zgJRC,iv:yr2iggy32uYp5FevFtUeyEmnlm6qsSAxOzqRhGtPxLo=,tag:jdGcTH8pHBh/mQZhhiFLjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdE01ZFBqQ3F1RXNSVUtn
            Y1cvZzhVNmh3RWp2NXIxdUpKUVpmYUZzY3dJClB5aUpCb0duVnYyeWZ5NCsvYkYz
            TFRZcTd4SitUeHpwcWNVeFhIck9UcU0KLS0tIGRrU3AxS0hMZ2tRdTVZeUJFa2Rw
            bk9tNGVoam13bEYwS1dIbExsYlJVaE0Kc5O4Y8yvqPxIY4q3PLXYTBraIrXrwvhr
            zVsmqulScR5PwDh+2ZJR7t2uS2BiztkcxUKrUz7oUmH84xzmZWoWxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mckmj4nc85aj0kkn2h0culsgtucz9pnd9qvm2p7jnzlwlcqhry3sflchyf
    lastmodified: "2026-07-05T18:07:03Z"
    mac: ENC[AES256_GCM,data:/UhR0rHx1ehvCq4gK5+wD6+kpRVqb2U9+jAIYPUpEPiwAtVmGWLMowTPbVb8G32xpV/zvSA8Ql56MX38OaYachUDtpk2ZYPKcFHdk6DdZbypgw8+581/2hHqmT4gqTUCAe94D/BdQiImFVCriR99zQLWXharMZSS5LISjAX/0kc=,iv:chrwHYrWNvvTEw7Jx5Zp5a1YQ6cEoZ8MP+LMzgOSX68=,tag:tQD3ocGg7tAztJqRkBD2CA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
