apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket-raw
spec:
  generateBucketName: ceph-bkt-raw
  storageClassName: rook-ceph-communal-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket-inflight
spec:
  generateBucketName: ceph-bkt-inflight
  storageClassName: rook-ceph-communal-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket-processed
spec:
  generateBucketName: ceph-bkt-processed
  storageClassName: rook-ceph-communal-bucket
